### ISSUE TITLE
Null Values reported for Fv, SD1 and SM1 for ASCE 7-16 SDC D Structures where S1 >= 0.2

### ISSUE THREAD

**Issue by SpencerF1** [manrajsingh/seismic-maps#41]
Hello, as stated in the title, I am seeing null values referring me to Section 11.4.8 in ASCE 7-16. This provision states not to use Table 11.4-2 for Fv for SDC D structures with a value of S1 > 0.2. This is somewhat correct however it does not include the exceptions listed where it states that this limitation only applies to structures which are seismically isolated structures and structures with damping systems. If it is possible, I would suggest adding a user input for whether the structure has damping/isolation systems and to take this exception into account so that the user be given the correct values for Fv.

Thanks

**Comment by manrajsingh** [comment]
@SpencerF1 Could you give us parameters of your search?

@AliSumer-Git  looping you in.

**Comment by SpencerF1** [comment]
4470 Alvarado Canyon Rd, San Diego, CA 92120, USA
ASCE 7-16
Risk Cateogry II
Site Class D - Stiff Soil

**Comment by paisiello** [comment]
This is essentially the same issue as #26 which was inexplicably closed by the Owner. Please re-open #26 and address the issue. It should be a very simple fix.

**Comment by AliSumer-Git** [comment]
"null -See Section 11.4.8" is not an error. The engineer is expected to use and decide if 11.4.8 applies. If it doesn't apply, then again, engineer is expected to calculate the values given in ASCE 7 Fa Fv tables. USGS does not give these values for this reason, and I agree with them. 
I know this is frustrating, believe me, I am too.

**Comment by paisiello** [comment]
Thank you for taking the time to respond.

I am not claiming it is an error. Rather it is an incomplete calculation
and I think most engineers (in California anyway) would find it useful for
the website to provide the full calculation rather than having to do the
calculation by hand every time.

Since the overwhelming vast super-majority of project sites in California
would have one of the Exceptions of 11.4.8 or 20.3.1 apply, I don't quite
understand the reluctance to make this seemingly small modification. Is the
intent of the website to cater only to the relatively small number of
large-scale projects like hospitals and high-rise buildings?

**Comment by AliSumer-Git** [comment]
This is not about size of projects or the location, since the website map is across USA, not just CA.
It is really not a choice of showing the data, the data doesn't exist in USGS servers. The website is showing what the server provides. Since an engineering decision is required in 11.4.8, you'll not get a value from USGS. 

There will be a fix in ASCE 7 Supplement #3, that may change the data in the following months (hopefully).

**Comment by paisiello** [comment]
I think you have it backwards. There is no engineering decision to be made.
I am not asking for any more data. The website would just be more
convenient to use if the complete calculation were provided so I don't have
to do it myself every time.

ASCE hazard tool will be free to the public in December. I'll probably just
use that website instead.
