### ISSUE TITLE
Service Error Timeout issue

### ISSUE THREAD

**Issue by Vincisolar** [manrajsingh/seismic-maps#56]
Lately when using this program, I get this message:
"USGS service error:
timeout(0)"
This has not been an issue in the past, but for the last month or so, this has been consistent when using your search by address function
<img width="1088" alt="image" src="https://github.com/manrajsingh/seismic-maps/assets/95710279/f2d46e32-2595-4c2d-b2aa-3213c8723fc5">

**Comment by lstrahm** [comment]
I've been having the same issue - USGS Service Error.  Usually, it's cleared up within a few minutes.  But today, it's been persistent.

**Comment by USGSFail** [comment]
USGS Service Error
timeout(0)
OSHPOD Seismic Design Maps has always delivered seismic coefficients when I enter project parameters and coordinates or address.  I have tried to use the site between 10 and 20 times today with no luck.  Is there anything I can do to fix the problem?

**Comment by UESMichael** [comment]
I've been getting a "time-out" error message since last Thursday.

**Comment by lstrahm** [comment]
I was finally able to use it within the last half-hour or so. Sent from Mail for Windows From: UESMichaelSent: Monday, August 7, 2023 10:43 AMTo: manrajsingh/seismic-mapsCc: lstrahm; CommentSubject: Re: [manrajsingh/seismic-maps] Service Error Timeout issue (Issue #56) I've been getting a "time-out" error message since last Thursday.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by manrajsingh** [comment]
USGS web services were down for some period of time and as a result this tool wasn't operational, resulting in timeout error. USGS web services are now operational so this tool should work as expected.

**Comment by USGSFail** [comment]
Great!  Many thanks!


[LEE + RO Water Infrastructure Engineers]<http://www.lee-ro.com/>
Alice Maupin, PE, SE
Supervising Structural Engineer
Celebrating 40 years as partners in possibility.
Los Angeles + Orange County
1199 South Fullerton Road
City of Industry, CA 91748

T 626-667-5373<tel:6266675373>
C 213-505-7579

website<http://www.lee-ro.com/> · ***@***.***,-117.9075448,17z/data=!3m1!4b1!4m5!3m4!1s0x80c32a689d96ef79:0x61b44cab80f3724c!8m2!3d33.9977936!4d-117.9053561>
